### ISSUE TITLE
ye sab kya ho rha hai : )

### ISSUE THREAD

**Issue by DiviyamPathak** [anurag3301/Assignments#3]
agar tere kisi ache aur pyaare dushman ne teacher ko dikha dia phir kya hoga.
itna sachai nei dikhate github pr

**Comment by anurag3301** [comment]
Are chill Biro, ye sab mere class ke log nahi hai na hi mere college ke assignment, ye sab classgap par mile log hai bahar ke, unke assignment me help ki hai ya banaya hai. College chutiya hai mera, idhar bas febinacci aur palindrome hota hai 😆

**Comment by DiviyamPathak** [comment]
acche kam kr rahe ho tum tarakki karoge

**Comment by anurag3301** [comment]
Hehe
